spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/DockerStudentDB?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
server:
  port: 8089